# Generated by Django 3.0.14 on 2025-12-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Medicine')),
            ],
        ),
    ]
